# Stage 1: Build Angular SPA
FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Stage 2: Nginx Web Server Runner
FROM nginx:alpine

# Copy built assets
COPY --from=builder /usr/src/app/dist/verix-frontend /usr/share/nginx/html

# Copy server config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
